// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using USQLCSharp.DataAccess;

namespace USQLCSharp.Migrations
{
    [DbContext(typeof(PeopleContext))]
    [Migration("20210409072210_Test5")]
    partial class Test5
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("USQLCSharp.Models.Contact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("EmailAddress")
                        .HasColumnType("text");

                    b.Property<int?>("PersonId")
                        .HasColumnType("int");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.ToTable("Contacts");
                });

            modelBuilder.Entity("USQLCSharp.Models.Device", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Ip")
                        .HasColumnType("text");

                    b.Property<string>("Mac")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int?>("PersonId")
                        .HasColumnType("int");

                    b.Property<int>("Rssi")
                        .HasColumnType("int");

                    b.Property<bool>("State")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Topic")
                        .HasColumnType("text");

                    b.Property<int>("Uptime")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.ToTable("Devices");
                });

            modelBuilder.Entity("USQLCSharp.Models.Parameter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Data")
                        .HasColumnType("text");

                    b.Property<int?>("DeviceId")
                        .HasColumnType("int");

                    b.Property<int>("DeviseId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Topic")
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.ToTable("Parameters");
                });

            modelBuilder.Entity("USQLCSharp.Models.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Birthsday")
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("People");
                });

            modelBuilder.Entity("USQLCSharp.Models.PersonState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Admittance")
                        .HasColumnType("int");

                    b.Property<int?>("PersonId")
                        .HasColumnType("int");

                    b.Property<bool>("SubmitEmailAddress")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("SubmitPhoneNumber")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.ToTable("PersonStates");
                });

            modelBuilder.Entity("USQLCSharp.Models.Contact", b =>
                {
                    b.HasOne("USQLCSharp.Models.Person", null)
                        .WithMany("Contacts")
                        .HasForeignKey("PersonId");
                });

            modelBuilder.Entity("USQLCSharp.Models.Device", b =>
                {
                    b.HasOne("USQLCSharp.Models.Person", null)
                        .WithMany("Devices")
                        .HasForeignKey("PersonId");
                });

            modelBuilder.Entity("USQLCSharp.Models.Parameter", b =>
                {
                    b.HasOne("USQLCSharp.Models.Device", null)
                        .WithMany("Parameters")
                        .HasForeignKey("DeviceId");
                });

            modelBuilder.Entity("USQLCSharp.Models.PersonState", b =>
                {
                    b.HasOne("USQLCSharp.Models.Person", null)
                        .WithMany("PersonStates")
                        .HasForeignKey("PersonId");
                });
#pragma warning restore 612, 618
        }
    }
}
